### PR TITLE
Bump and Build v1.3.5

### PR DESCRIPTION
**Pull request by paulfalgout**

### CODE REVIEW

**Comment by ianmstew** [comment]
It's strange that this one doesn't have a changed map, but babysitter does https://github.com/marionettejs/backbone.babysitter/pull/63/files.  That doesn't mean anything does it?

**Comment by paulfalgout** [comment]
Yeah.. so I deleted the map file and rebuilt, and it did get built..  but no changes?  I can't tell what's actually different on baby-sitter either as to why it did commit it..

**Comment by ianmstew** [comment]
Okay, interesting.  Thanks for double-checking.  :+1: @ahumphreys87

**Comment by paulfalgout** [comment]
So now I'm really paranoid about the map. most other PRs do have it.  I bumped up my uglify a 0.0.1 and ran it again which produced what's in this PR.  I had some trouble getting the build to work without messing with deps as it is, so I might see if I can get a solid build with some devdep bumps.   similar to https://github.com/marionettejs/backbone.wreqr/pull/68 for a separate PR.
It looks like it just changed the sources, which previously was just "?" and move file up to the top.. 
So that said, I'm about as confident as I ever am that the map is good.

Thoughts?  Concerns?

**Comment by ianmstew** [comment]
I did a comparison of the token strings, and it looks like there are 6 differences out of about 600 tokens.  Something definitely changed in the map.  I can't speak to _why_ it changed now when it didn't before, but I'm confident at least that we do have an updated map.

**Comment by ahumphreys87** [comment]
manually merged

**Pull request closed without merging**
